name=input("enter your  name        :")
age=int(input("enter your age       :"))
print("your name is ",name,"your age is ",age,"years old")
print(age  +5 )
num1=int(input("enter number 1    "))
num2=int(input("enter number  2       "))
print("sum is ",num1+num2)